name: Aider on Issue Labeled

on:
  issues:
    types: [labeled]

jobs:
  generate:
    uses: ao-org/.github/.github/workflows/aider-on-issue-labeled.yml@master
    with:
      issue-number: ${{ github.event.issue.number }}
      base-branch: ${{ github.event.repository.default_branch }}
    secrets:
      anthropic_api_key: ${{ secrets.anthropic_api_key }}
